<?php
$otp=random_int(00000,99999);
$to_email = "21bmiit100@gmail.com";
$subject = "Mail Successfull 🥳";
$body = "Hi i am taxi dash officialy created by may creators naishal , navdeep and pranav\n otp generated by me is $otp";
$headers = "From: dashtaxigg@gmail.com";

if (mail($to_email, $subject, $body, $headers)) {
    echo "Email successfully sent to $to_email...";
} else {
    echo "Email sending failed...";
}